#ifndef LIBANGLE_RENDERER_VULKAN_VULKAN_GPU_SPVFILE_H_
#define LIBANGLE_RENDERER_VULKAN_VULKAN_GPU_SPVFILE_H_
#include "spv/GL_ETC1_RGB8_OES.spv.h"
          
#include "spv/GL_COMPRESSED_R11_EAC.spv.h"
#include "spv/GL_COMPRESSED_SIGNED_R11_EAC.spv.h"
#include "spv/GL_COMPRESSED_RG11_EAC.spv.h"
#include "spv/GL_COMPRESSED_SIGNED_RG11_EAC.spv.h"
#include "spv/GL_COMPRESSED_RGB8_ETC2.spv.h"
#include "spv/GL_COMPRESSED_SRGB8_ETC2.spv.h"
#include "spv/GL_COMPRESSED_RGBA8_ETC2_EAC.spv.h"
#include "spv/GL_COMPRESSED_SRGB8_ALPHA8_ETC2_EAC.spv.h"
#include "spv/GL_COMPRESSED_RGB8_PUNCHTHROUGH_ALPHA1_ETC2.spv.h"
#include "spv/GL_COMPRESSED_SRGB8_PUNCHTHROUGH_ALPHA1_ETC2.spv.h"
          
#include "spv/GL_COMPRESSED_RGBA_ASTC_4x4.spv.h"
#include "spv/GL_COMPRESSED_RGBA_ASTC_5x4.spv.h"
#include "spv/GL_COMPRESSED_RGBA_ASTC_5x5.spv.h"
#include "spv/GL_COMPRESSED_RGBA_ASTC_6x5.spv.h"
#include "spv/GL_COMPRESSED_RGBA_ASTC_6x6.spv.h"
#include "spv/GL_COMPRESSED_RGBA_ASTC_8x5.spv.h"
#include "spv/GL_COMPRESSED_RGBA_ASTC_8x6.spv.h"
#include "spv/GL_COMPRESSED_RGBA_ASTC_8x8.spv.h"
#include "spv/GL_COMPRESSED_RGBA_ASTC_10x5.spv.h"
#include "spv/GL_COMPRESSED_RGBA_ASTC_10x6.spv.h"
#include "spv/GL_COMPRESSED_RGBA_ASTC_10x8.spv.h"
#include "spv/GL_COMPRESSED_RGBA_ASTC_10x10.spv.h"
#include "spv/GL_COMPRESSED_RGBA_ASTC_12x10.spv.h"
#include "spv/GL_COMPRESSED_RGBA_ASTC_12x12.spv.h"
#include "spv/GL_COMPRESSED_SRGB8_ALPHA8_ASTC_4x4.spv.h"
#include "spv/GL_COMPRESSED_SRGB8_ALPHA8_ASTC_5x4.spv.h"
#include "spv/GL_COMPRESSED_SRGB8_ALPHA8_ASTC_5x5.spv.h"
#include "spv/GL_COMPRESSED_SRGB8_ALPHA8_ASTC_6x5.spv.h"
#include "spv/GL_COMPRESSED_SRGB8_ALPHA8_ASTC_6x6.spv.h"
#include "spv/GL_COMPRESSED_SRGB8_ALPHA8_ASTC_8x5.spv.h"
#include "spv/GL_COMPRESSED_SRGB8_ALPHA8_ASTC_8x6.spv.h"
#include "spv/GL_COMPRESSED_SRGB8_ALPHA8_ASTC_8x8.spv.h"
#include "spv/GL_COMPRESSED_SRGB8_ALPHA8_ASTC_10x5.spv.h"
#include "spv/GL_COMPRESSED_SRGB8_ALPHA8_ASTC_10x6.spv.h"
#include "spv/GL_COMPRESSED_SRGB8_ALPHA8_ASTC_10x8.spv.h"
#include "spv/GL_COMPRESSED_SRGB8_ALPHA8_ASTC_10x10.spv.h"
#include "spv/GL_COMPRESSED_SRGB8_ALPHA8_ASTC_12x10.spv.h"
#include "spv/GL_COMPRESSED_SRGB8_ALPHA8_ASTC_12x12.spv.h"



namespace shader_spv
{

typedef struct
{
    const char *name;
    const unsigned char *base;
    size_t size;  // bytes; please convert to uint32's later
} SpvData;

const SpvData sDecompressionShaderData[] = {
    {"GL_COMPRESSED_RGBA_ASTC_4x4.spv", GL_COMPRESSED_RGBA_ASTC_4x4_spv,
     sizeof(GL_COMPRESSED_RGBA_ASTC_4x4_spv)},
    {"GL_COMPRESSED_RGBA_ASTC_5x4.spv", GL_COMPRESSED_RGBA_ASTC_5x4_spv,
     sizeof(GL_COMPRESSED_RGBA_ASTC_5x4_spv)},
    {"GL_COMPRESSED_RGBA_ASTC_5x5.spv", GL_COMPRESSED_RGBA_ASTC_5x5_spv,
     sizeof(GL_COMPRESSED_RGBA_ASTC_5x5_spv)},
    {"GL_COMPRESSED_RGBA_ASTC_6x5.spv", GL_COMPRESSED_RGBA_ASTC_6x5_spv,
     sizeof(GL_COMPRESSED_RGBA_ASTC_6x5_spv)},
    {"GL_COMPRESSED_RGBA_ASTC_6x6.spv", GL_COMPRESSED_RGBA_ASTC_6x6_spv,
     sizeof(GL_COMPRESSED_RGBA_ASTC_6x6_spv)},
    {"GL_COMPRESSED_RGBA_ASTC_8x5.spv", GL_COMPRESSED_RGBA_ASTC_8x5_spv,
     sizeof(GL_COMPRESSED_RGBA_ASTC_8x5_spv)},
    {"GL_COMPRESSED_RGBA_ASTC_8x6.spv", GL_COMPRESSED_RGBA_ASTC_8x6_spv,
     sizeof(GL_COMPRESSED_RGBA_ASTC_8x6_spv)},
    {"GL_COMPRESSED_RGBA_ASTC_8x8.spv", GL_COMPRESSED_RGBA_ASTC_8x8_spv,
     sizeof(GL_COMPRESSED_RGBA_ASTC_8x8_spv)},
    {"GL_COMPRESSED_RGBA_ASTC_10x5.spv", GL_COMPRESSED_RGBA_ASTC_10x5_spv,
     sizeof(GL_COMPRESSED_RGBA_ASTC_10x5_spv)},
    {"GL_COMPRESSED_RGBA_ASTC_10x6.spv", GL_COMPRESSED_RGBA_ASTC_10x6_spv,
     sizeof(GL_COMPRESSED_RGBA_ASTC_10x6_spv)},
    {"GL_COMPRESSED_RGBA_ASTC_10x8.spv", GL_COMPRESSED_RGBA_ASTC_10x8_spv,
     sizeof(GL_COMPRESSED_RGBA_ASTC_10x8_spv)},
    {"GL_COMPRESSED_RGBA_ASTC_10x10.spv", GL_COMPRESSED_RGBA_ASTC_10x10_spv,
     sizeof(GL_COMPRESSED_RGBA_ASTC_10x10_spv)},
    {"GL_COMPRESSED_RGBA_ASTC_12x10.spv", GL_COMPRESSED_RGBA_ASTC_12x10_spv,
     sizeof(GL_COMPRESSED_RGBA_ASTC_12x10_spv)},
    {"GL_COMPRESSED_RGBA_ASTC_12x12.spv", GL_COMPRESSED_RGBA_ASTC_12x12_spv,
     sizeof(GL_COMPRESSED_RGBA_ASTC_12x12_spv)},
    {"GL_COMPRESSED_SRGB8_ALPHA8_ASTC_4x4.spv", GL_COMPRESSED_SRGB8_ALPHA8_ASTC_4x4_spv,
     sizeof(GL_COMPRESSED_SRGB8_ALPHA8_ASTC_4x4_spv)},
    {"GL_COMPRESSED_SRGB8_ALPHA8_ASTC_5x4.spv", GL_COMPRESSED_SRGB8_ALPHA8_ASTC_5x4_spv,
     sizeof(GL_COMPRESSED_SRGB8_ALPHA8_ASTC_5x4_spv)},
    {"GL_COMPRESSED_SRGB8_ALPHA8_ASTC_5x5.spv", GL_COMPRESSED_SRGB8_ALPHA8_ASTC_5x5_spv,
     sizeof(GL_COMPRESSED_SRGB8_ALPHA8_ASTC_5x5_spv)},
    {"GL_COMPRESSED_SRGB8_ALPHA8_ASTC_6x5.spv", GL_COMPRESSED_SRGB8_ALPHA8_ASTC_6x5_spv,
     sizeof(GL_COMPRESSED_SRGB8_ALPHA8_ASTC_6x5_spv)},
    {"GL_COMPRESSED_SRGB8_ALPHA8_ASTC_6x6.spv", GL_COMPRESSED_SRGB8_ALPHA8_ASTC_6x6_spv,
     sizeof(GL_COMPRESSED_SRGB8_ALPHA8_ASTC_6x6_spv)},
    {"GL_COMPRESSED_SRGB8_ALPHA8_ASTC_8x5.spv", GL_COMPRESSED_SRGB8_ALPHA8_ASTC_8x5_spv,
     sizeof(GL_COMPRESSED_SRGB8_ALPHA8_ASTC_8x5_spv)},
    {"GL_COMPRESSED_SRGB8_ALPHA8_ASTC_8x6.spv", GL_COMPRESSED_SRGB8_ALPHA8_ASTC_8x6_spv,
     sizeof(GL_COMPRESSED_SRGB8_ALPHA8_ASTC_8x6_spv)},
    {"GL_COMPRESSED_SRGB8_ALPHA8_ASTC_8x8.spv", GL_COMPRESSED_SRGB8_ALPHA8_ASTC_8x8_spv,
     sizeof(GL_COMPRESSED_SRGB8_ALPHA8_ASTC_8x8_spv)},
    {"GL_COMPRESSED_SRGB8_ALPHA8_ASTC_10x5.spv", GL_COMPRESSED_SRGB8_ALPHA8_ASTC_10x5_spv,
     sizeof(GL_COMPRESSED_SRGB8_ALPHA8_ASTC_10x5_spv)},
    {"GL_COMPRESSED_SRGB8_ALPHA8_ASTC_10x6.spv", GL_COMPRESSED_SRGB8_ALPHA8_ASTC_10x6_spv,
     sizeof(GL_COMPRESSED_SRGB8_ALPHA8_ASTC_10x6_spv)},
    {"GL_COMPRESSED_SRGB8_ALPHA8_ASTC_10x8.spv", GL_COMPRESSED_SRGB8_ALPHA8_ASTC_10x8_spv,
     sizeof(GL_COMPRESSED_SRGB8_ALPHA8_ASTC_10x8_spv)},
    {"GL_COMPRESSED_SRGB8_ALPHA8_ASTC_10x10.spv", GL_COMPRESSED_SRGB8_ALPHA8_ASTC_10x10_spv,
     sizeof(GL_COMPRESSED_SRGB8_ALPHA8_ASTC_10x10_spv)},
    {"GL_COMPRESSED_SRGB8_ALPHA8_ASTC_12x10.spv", GL_COMPRESSED_SRGB8_ALPHA8_ASTC_12x10_spv,
     sizeof(GL_COMPRESSED_SRGB8_ALPHA8_ASTC_12x10_spv)},
    {"GL_COMPRESSED_SRGB8_ALPHA8_ASTC_12x12.spv", GL_COMPRESSED_SRGB8_ALPHA8_ASTC_12x12_spv,
     sizeof(GL_COMPRESSED_SRGB8_ALPHA8_ASTC_12x12_spv)},
    {"GL_ETC1_RGB8_OES.spv", GL_ETC1_RGB8_OES_spv, sizeof(GL_ETC1_RGB8_OES_spv)},
    {"GL_COMPRESSED_RGB8_ETC2.spv", GL_COMPRESSED_RGB8_ETC2_spv,
     sizeof(GL_COMPRESSED_RGB8_ETC2_spv)},
    {"GL_COMPRESSED_RGBA8_ETC2_EAC.spv", GL_COMPRESSED_RGBA8_ETC2_EAC_spv,
     sizeof(GL_COMPRESSED_RGBA8_ETC2_EAC_spv)},
    {"GL_COMPRESSED_RGB8_PUNCHTHROUGH_ALPHA1_ETC2.spv",
     GL_COMPRESSED_RGB8_PUNCHTHROUGH_ALPHA1_ETC2_spv,
     sizeof(GL_COMPRESSED_RGB8_PUNCHTHROUGH_ALPHA1_ETC2_spv)},
    {"GL_COMPRESSED_SRGB8_ETC2.spv", GL_COMPRESSED_SRGB8_ETC2_spv,
     sizeof(GL_COMPRESSED_SRGB8_ETC2_spv)},
    {"GL_COMPRESSED_SRGB8_ALPHA8_ETC2_EAC.spv", GL_COMPRESSED_SRGB8_ALPHA8_ETC2_EAC_spv,
     sizeof(GL_COMPRESSED_SRGB8_ALPHA8_ETC2_EAC_spv)},
    {"GL_COMPRESSED_SRGB8_PUNCHTHROUGH_ALPHA1_ETC2.spv",
     GL_COMPRESSED_SRGB8_PUNCHTHROUGH_ALPHA1_ETC2_spv,
     sizeof(GL_COMPRESSED_SRGB8_PUNCHTHROUGH_ALPHA1_ETC2_spv)},
    {"GL_COMPRESSED_R11_EAC.spv", GL_COMPRESSED_R11_EAC_spv, sizeof(GL_COMPRESSED_R11_EAC_spv)},
    {"GL_COMPRESSED_SIGNED_R11_EAC.spv", GL_COMPRESSED_SIGNED_R11_EAC_spv,
     sizeof(GL_COMPRESSED_SIGNED_R11_EAC_spv)},
    {"GL_COMPRESSED_RG11_EAC.spv", GL_COMPRESSED_RG11_EAC_spv, sizeof(GL_COMPRESSED_RG11_EAC_spv)},
    {"GL_COMPRESSED_SIGNED_RG11_EAC.spv", GL_COMPRESSED_SIGNED_RG11_EAC_spv,
     sizeof(GL_COMPRESSED_SIGNED_RG11_EAC_spv)},
}; 

}  // namespace shader_spv

#endif